### ISSUE TITLE
Dist version link ?

### ISSUE THREAD

**Issue by FlashPapa** [r-park/angular2-webpack-seed#12]
Hi, You have done a great job, congrats !
I have just a little question, when i use `gulp dist` , it makes an target/index.html like that ->
```
<!DOCTYPE html>
<html lang="en">
<head>
  <base href="/">
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <title>Angular2 Webpack Seed</title>
<link href="/styles.css?a1765fa82196bb63b67f" rel="stylesheet"></head>
<body>
  <app></app>
<script src="/vendor.js?a1765fa82196bb63b67f"></script><script src="/main.js?a1765fa82196bb63b67f"></script></body>
</html>
```

But when i want to test the project in my localhost -> http://127.0.0.1/mydir/angular2-webpack-seed, the links are bad so i must do 

```
<!DOCTYPE html>
<html lang="en">
<head>
  <base href="http://127.0.0.1/mydir/angular2-webpack-seed/target/">
<meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
<title>Angular2 Webpack Seed</title>
<link href="./styles.css?a1765fa82196bb63b67f" rel="stylesheet"></head>
<body>
  <app></app>
<script src="./vendor.js?a1765fa82196bb63b67f"></script><script src="./main.js?a1765fa82196bb63b67f"></script></body>
</html>
```

Have you got a trick or params to change that easily ?
Thanking you in advance
Flashpapa

**Comment by r-park** [comment]
Hi @FlashPapa — you can try changing the `publicPath` [setting](https://github.com/r-park/angular2-webpack-seed/blob/master/webpack.dist.js#L35) in `webpack.dist.js` to:
```javascript
publicPath: '/mydir/angular2-webpack-seed/target'
```
Alternatively, if you just want to try out the built project without webpack, there is a BrowserSync server available by running:
```javascript
$ gulp serve
```
This will:
- start a BrowserSync server at http://localhost:3000
- serve the files in `/target` that were created by `gulp dist`.

**Comment by FlashPapa** [comment]
Ok,
Thanks a lot ! I will test this quickly,
Best regards
