### ISSUE TITLE
Question on linking CSS file

### ISSUE THREAD

**Issue by AlexZhidkov** [r-park/angular2-webpack-seed#26]
HI, I'm building an app based on your todo-angular2-firebase example and I want to use Angular2-Toaster library. Can you help me to figure out how to link toaster.css using webpack? Normally it's <link rel="stylesheet" type="text/css" href="/node_modules/angular2-toaster/lib/toaster.css" />. How do I do it in a webpack?

**Comment by r-park** [comment]
Hi @AlexZhidkov 

I've added [CopyWebpackPlugin](https://github.com/kevlened/copy-webpack-plugin) (see commit d34dd8e4a1f31550c7aae9fa3f81a8a9978a076a)

To get the `Angular2-Toaster` css working, replace the example `link` tag in [index.html](https://github.com/r-park/angular2-webpack-seed/blob/master/src/index.html#L12) with your own:
```html
<link rel="stylesheet" href="toaster.css">
```
In [webpack.base.js](https://github.com/r-park/angular2-webpack-seed/blob/master/webpack.base.js#L6) add the path to the `toaster.css` file into the `assets` array:
```javascript
assets: [
    {from: 'node_modules/angular2-toaster/lib/toaster.css'}
]
```
When running in dev mode via `$ gulp` or `$ npm start` webpack will load the css file from memory. 

When building your production bundle via `$ gulp dist` webpack will copy the css file to the target directory.

**Comment by AlexZhidkov** [comment]
Thank you very much! You're so helpfull! I will test this later today and close the issue.

**Comment by AlexZhidkov** [comment]
Beautiful! Works like a charm!
