### ISSUE TITLE
[not-an-issue] json-loader inclusion in project

### ISSUE THREAD

**Issue by jdiapps** [r-park/angular2-webpack-seed#38]
I am trying to add json-loader to the project and use it to load config.json files in my app.

I added the following to my webpack.config.js file, but it is not pulling the config.json file and including it in the production bundle.

config.module = {
  loaders: [
    { test: /\.json$/, loader: "json" },
    {test: /\.ts$/, loader: 'ts', exclude: /node_modules/},
    {test: /\.html$/, loader: 'raw'},
    {test: /\.scss$/, loader: 'raw!postcss!sass', exclude: path.resolve('src/views/common/styles'), include: path.resolve('src/views')}
  ]
};

Would you be able to include json-loader as a loader in the github project with a config.json file at the root of the project?

Not sure what I'm missing, but this would be a big help for apps that need configuration data in the bundle.

Thanks

**Comment by r-park** [comment]
Hi @jdiapps — this should be resolved by https://github.com/r-park/angular2-webpack-seed/commit/aec350a1efaddd88af4c711c6f38e8e7c3ea22c4

Example:
```js
// config.json @ project root
{
  "foo": "bar",
  "biz": [{
    "baz": 123
  }]
}
```
```ts
// src/main.ts
const config = require('../config.json')
console.log('config:', config) //=> {foo: bar, ... }
```

**Comment by jdiapps** [comment]
Awesome!!!  

Thanks
