### ISSUE TITLE
[question] Change npm run server to serve files from non localhost

### ISSUE THREAD

**Issue by jdiapps** [r-park/angular2-webpack-seed#42]
How do I change main.js under server to dish the application from localhost:3000 to 

https://myurl.dev.com:9000?

Notice the https.

Thanks for the help.

**Comment by r-park** [comment]
Hey @jdiapps

Set environment variables for `HOST` and `PORT` in your server environment and the [config file](https://github.com/r-park/angular2-webpack-seed/blob/master/server/main.js#L19) will pick it up. You can of course customize the var names to suit your needs.

**Comment by r-park** [comment]
Missed the part about `https` — the express server in this repo isn't configured for ssl.

**Comment by jdiapps** [comment]
Got it figured out using webpack-dev-server.  

In the webpack.config.js change this to:
const HOST = process.env.HOST || '0.0.0.0';
0.0.0.0 will bind to all hosts.

for the https part i added the switch --https in package.json:
"server:dev": "cross-env NODE_ENV=development webpack-dev-server --progress --https",
