### ISSUE TITLE
[Not An Issue]Question:  How does webpack remove spec files from production bundle

### ISSUE THREAD

**Issue by jdiapps** [r-park/angular2-webpack-seed#46]
I am noticing that npm run build, removes all the unit test files in it's production build.

Is something you did in the configuration files, or does webpack automagically remove the spec files in the final build.

Thanks

**Comment by r-park** [comment]
Hey @jdiapps — webpack uses the [entry file](https://github.com/r-park/angular2-webpack-seed/blob/master/webpack.config.js#L117) to trace and resolve all the imports required by the app. As a result, specs are excluded because they aren't imported by the app sources.
